# Generated by Django 5.2.4 on 2025-08-25 10:13

import evaluations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_appraisalanalytics_appraisalformtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationperiod',
            name='submission_deadline',
            field=models.DateTimeField(default=evaluations.models.get_default_submission_deadline),
        ),
    ]
