# Generated by Django 5.2.4 on 2025-08-24 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_permission_permissionaudit_permissiongroup_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisorrelationship',
            options={'ordering': ['supervisor__username', 'subordinate__username']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['user__username', 'role']},
        ),
        migrations.RemoveIndex(
            model_name='profileupdaterequest',
            name='users_profi_user_id_41c830_idx',
        ),
        migrations.RemoveIndex(
            model_name='profileupdaterequest',
            name='users_profi_status_97171f_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='users_user__employe_0741f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='users_user__departm_b39f2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='users_user__is_acti_36a403_idx',
        ),
        migrations.RemoveField(
            model_name='actingappointment',
            name='appointment_type',
        ),
        migrations.RemoveField(
            model_name='actingappointment',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='profileupdaterequest',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='staffqualification',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='staffqualification',
            name='is_acquired_during_period',
        ),
        migrations.RemoveField(
            model_name='staffqualification',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stafftraining',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='stafftraining',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='stafftraining',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_salary_contiss',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_salary_step',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_first_appointment',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_first_appointment_nbrri',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='present_substantive_post',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='present_substantive_post_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_approved_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_approved_by',
        ),
        migrations.AddField(
            model_name='actingappointment',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AddField(
            model_name='actingappointment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='actingappointment',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profileupdaterequest',
            name='current_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profileupdaterequest',
            name='requested_changes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='staffqualification',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffqualification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffqualification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffqualification',
            name='qualification_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stafftraining',
            name='certificate_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stafftraining',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stafftraining',
            name='impact_on_work',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stafftraining',
            name='skills_acquired',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stafftraining',
            name='training_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stafftraining',
            name='training_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='actingappointment',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='actingappointment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position'),
        ),
        migrations.AlterField(
            model_name='profileupdaterequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileupdaterequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_requests_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileupdaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffqualification',
            name='institution',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='staffqualification',
            name='qualification_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stafftraining',
            name='institution',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_update_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('hr', 'Human Resources'), ('supervisor', 'Supervisor'), ('staff', 'Staff Member'), ('review_panel', 'Review Panel')], default='staff', max_length=20),
        ),
        migrations.AlterModelTable(
            name='actingappointment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='profileupdaterequest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='staffqualification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='stafftraining',
            table=None,
        ),
        migrations.AlterModelTable(
            name='supervisorrelationship',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userrole',
            table=None,
        ),
    ]
