# Generated by Django 5.2.4 on 2025-08-25 10:13

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_supervisorrelationship_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actingappointment',
            name='end_date',
            field=models.DateField(default=users.models.get_default_end_date),
        ),
    ]
