# Generated by Django 5.2.4 on 2025-08-24 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(default='', max_length=100, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('permission_type', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('export', 'Export'), ('import', 'Import'), ('assign', 'Assign'), ('delegate', 'Delegate'), ('override', 'Override'), ('view_analytics', 'View Analytics'), ('manage_users', 'Manage Users'), ('configure_system', 'Configure System')], default='read', max_length=20)),
                ('resource_type', models.CharField(choices=[('evaluation', 'Evaluation'), ('kpi', 'KPI'), ('form_template', 'Form Template'), ('goal', 'Goal'), ('approval', 'Approval'), ('analytics', 'Analytics'), ('user', 'User'), ('department', 'Department'), ('role', 'Role'), ('permission', 'Permission'), ('system_config', 'System Configuration'), ('audit_log', 'Audit Log'), ('notification', 'Notification'), ('report', 'Report')], default='evaluation', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_permission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['resource_type', 'permission_type'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('granted', 'Permission Granted'), ('revoked', 'Permission Revoked'), ('modified', 'Permission Modified'), ('override_granted', 'Override Granted'), ('override_revoked', 'Override Revoked'), ('role_assigned', 'Role Assigned'), ('role_removed', 'Role Removed')], default='granted', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('codename', models.CharField(default='', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(choices=[('grant', 'Grant'), ('deny', 'Deny'), ('modify', 'Modify')], default='grant', max_length=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('codename', models.CharField(default='', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('role_type', models.CharField(choices=[('system', 'System Role'), ('department', 'Department Role'), ('project', 'Project Role'), ('temporary', 'Temporary Role'), ('functional', 'Functional Role'), ('leadership', 'Leadership Role'), ('specialist', 'Specialist Role')], default='system', max_length=20)),
                ('role_level', models.CharField(choices=[('entry', 'Entry Level'), ('junior', 'Junior Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead Level'), ('manager', 'Manager Level'), ('director', 'Director Level'), ('executive', 'Executive Level')], default='mid', max_length=20)),
                ('max_subordinates', models.PositiveIntegerField(default=0)),
                ('can_approve_evaluations', models.BooleanField(default=False)),
                ('can_create_evaluations', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_configure_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='approvalworkflowlevel',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['title']},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_audit__user_id_66db5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_audit__model_n_5ea3b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_audit__action_1cc579_idx',
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='approvalworkflowlevel',
            name='is_required',
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='level',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='approvallevel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='approvalworkflowlevel',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('approve', 'Approve'), ('reject', 'Reject'), ('submit', 'Submit')], default='create', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='position',
            name='contiss_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='key',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='value',
            field=models.TextField(default=''),
        ),
        migrations.AlterModelTable(
            name='approvallevel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='approvalworkflow',
            table=None,
        ),
        migrations.AlterModelTable(
            name='approvalworkflowlevel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
        migrations.AlterModelTable(
            name='position',
            table=None,
        ),
        migrations.AlterModelTable(
            name='systemconfiguration',
            table=None,
        ),
        migrations.AddField(
            model_name='permission',
            name='department_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='permissionaudit',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionaudit',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audits', to='core.permission'),
        ),
        migrations.AddField(
            model_name='permissionaudit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='permissions',
            field=models.ManyToManyField(related_name='permission_groups', to='core.permission'),
        ),
        migrations.AddField(
            model_name='permissionoverride',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionoverride',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='core.permission'),
        ),
        migrations.AddField(
            model_name='permissionoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionaudit',
            name='override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.permissionoverride'),
        ),
        migrations.AddField(
            model_name='role',
            name='approval_required_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_roles', to='core.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_kpis_for',
            field=models.ManyToManyField(blank=True, related_name='kpis_created_by_roles', to='core.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_evaluate_roles',
            field=models.ManyToManyField(blank=True, related_name='evaluated_by_roles', to='core.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_roles',
            field=models.ManyToManyField(blank=True, related_name='managed_by_roles', to='core.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='role',
            name='parent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='core.role'),
        ),
        migrations.AddField(
            model_name='permissionaudit',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_user_roles', to='core.department'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['codename'], name='core_permis_codenam_1da12d_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['permission_type', 'resource_type'], name='core_permis_permiss_2a93ce_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['is_active'], name='core_permis_is_acti_04a15b_idx'),
        ),
        migrations.AddIndex(
            model_name='permissiongroup',
            index=models.Index(fields=['codename'], name='core_permis_codenam_b31140_idx'),
        ),
        migrations.AddIndex(
            model_name='permissiongroup',
            index=models.Index(fields=['is_active'], name='core_permis_is_acti_683f57_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionoverride',
            index=models.Index(fields=['user', 'is_active', 'start_date'], name='core_permis_user_id_5850d6_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionoverride',
            index=models.Index(fields=['permission', 'is_active'], name='core_permis_permiss_823eba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permissionoverride',
            unique_together={('user', 'permission', 'override_type')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['codename'], name='core_role_codenam_3fda00_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['role_type', 'department'], name='core_role_role_ty_e0df1d_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['role_level'], name='core_role_role_le_639d80_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_active'], name='core_role_is_acti_cf5dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionaudit',
            index=models.Index(fields=['user', 'timestamp'], name='core_permis_user_id_6b1846_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionaudit',
            index=models.Index(fields=['permission', 'timestamp'], name='core_permis_permiss_4345f7_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionaudit',
            index=models.Index(fields=['action', 'timestamp'], name='core_permis_action_eb6c88_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionaudit',
            index=models.Index(fields=['performed_by', 'timestamp'], name='core_permis_perform_8a57f7_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'is_active'], name='core_rolepe_role_id_a136dc_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission', 'is_active'], name='core_rolepe_permiss_5e2aea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active', 'start_date'], name='core_userro_user_id_e14492_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'is_active'], name='core_userro_role_id_dccb6a_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['department', 'is_active'], name='core_userro_departm_4c0ea2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'department')},
        ),
    ]
