# Generated by Django 5.2.4 on 2025-08-24 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emaillog',
            name='notificatio_recipie_f944ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='emaillog',
            name='notificatio_status_7a5e03_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_f2e0f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_priorit_f7c359_idx',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='template_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='reminder_frequency',
        ),
        migrations.RemoveField(
            model_name='systemannouncement',
            name='message',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='system_announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemannouncement',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemannouncement',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('evaluation_submitted', 'Evaluation Submitted'), ('evaluation_approved', 'Evaluation Approved'), ('evaluation_rejected', 'Evaluation Rejected'), ('approval_required', 'Approval Required'), ('profile_update_request', 'Profile Update Request'), ('profile_update_approved', 'Profile Update Approved'), ('profile_update_rejected', 'Profile Update Rejected'), ('system_announcement', 'System Announcement'), ('reminder', 'Reminder')], default='reminder', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AlterModelTable(
            name='emaillog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='emailtemplate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='notificationpreference',
            table=None,
        ),
        migrations.AlterModelTable(
            name='systemannouncement',
            table=None,
        ),
    ]
