# Generated by Django 5.2.4 on 2025-08-25 10:13

import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_emaillog_notificatio_recipie_f944ad_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemannouncement',
            name='start_date',
            field=models.DateTimeField(default=notifications.models.get_default_start_date),
        ),
    ]
